In [1]:
#TEST NHOOD Process
import numpy as np
#Make Demo
testStack = np.zeros((4, 4, 4))
adder = 1
for i in range(testStack.shape[0]):
    for j in range(testStack.shape[1]):
        for k in range(testStack.shape[2]):
            testStack[i, j, k] = adder
            adder += 1
print(testStack)
#Test Subroutine
radius = 1
test_x = np.zeros((np.prod(testStack.shape), (radius*2 + 1)**3)) #shape (n_samples, n_features)
# print(np.prod(testStack.shape))
# print((radius*2 + 1)**3)
testStackPad = np.pad(testStack, ((radius,radius), (radius,radius), (radius,radius)), 
                    mode='constant', constant_values=(255, 255))
xRow = 0
for i in range(radius, testStackPad.shape[0] - radius):
    for j in range(radius, testStackPad.shape[1] - radius):
        for k in range(radius, testStackPad.shape[2] - radius):
            test_x[xRow] = testStackPad[i-radius:i+radius+1, j-radius:j+radius+1, 
                                        k-radius:k+radius+1].flatten()
#             print(testStackPad[i-radius:i+radius+1, j-radius:j+radius+1, k-radius:k+radius+1])
#             print(test_x[xRow])
#             sys.exit()
            xRow += 1
test_x

[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]
  [13. 14. 15. 16.]]

 [[17. 18. 19. 20.]
  [21. 22. 23. 24.]
  [25. 26. 27. 28.]
  [29. 30. 31. 32.]]

 [[33. 34. 35. 36.]
  [37. 38. 39. 40.]
  [41. 42. 43. 44.]
  [45. 46. 47. 48.]]

 [[49. 50. 51. 52.]
  [53. 54. 55. 56.]
  [57. 58. 59. 60.]
  [61. 62. 63. 64.]]]


array([[255., 255., 255., ..., 255.,  21.,  22.],
       [255., 255., 255., ...,  21.,  22.,  23.],
       [255., 255., 255., ...,  22.,  23.,  24.],
       ...,
       [ 41.,  42.,  43., ..., 255., 255., 255.],
       [ 42.,  43.,  44., ..., 255., 255., 255.],
       [ 43.,  44., 255., ..., 255., 255., 255.]])