In [48]:
#TEST NHOOD Process
import numpy as np
#Make Demo
testStack = np.zeros((4, 4, 3))
adder = 1
for i in range(testStack.shape[0]):
    for j in range(testStack.shape[1]):
        for k in range(testStack.shape[2]):
            testStack[i, j, k] = adder
            adder += 1
#Test Subroutine
radius = 1
test_x = np.zeros((np.prod(testStack.shape), (radius*2 + 1)**3)) #shape (n_samples, n_features)
# print(np.prod(testStack.shape))
# print((radius*2 + 1)**3)
testStackPad = np.pad(testStack, ((radius,radius), (radius,radius), (radius,radius)), 
                    mode='constant', constant_values=(255, 255))
xRow = 0
for i in range(radius, testStackPad.shape[0] - radius):
    for j in range(radius, testStackPad.shape[1] - radius):
        for k in range(radius, testStackPad.shape[2] - radius):
            test_x[xRow] = testStackPad[i-radius:i+radius+1, j-radius:j+radius+1, 
                                        k-radius:k+radius+1].flatten()
#             print(testStackPad[i-radius:i+radius+1, j-radius:j+radius+1, k-radius:k+radius+1])
#             print(test_x[xRow])
#             sys.exit()
            xRow += 1
print(testStack)
print(test_x[1])
print()
print(testStack.flatten())
print(testStackPad)

[[[ 1.  2.  3.]
  [ 4.  5.  6.]
  [ 7.  8.  9.]
  [10. 11. 12.]]

 [[13. 14. 15.]
  [16. 17. 18.]
  [19. 20. 21.]
  [22. 23. 24.]]

 [[25. 26. 27.]
  [28. 29. 30.]
  [31. 32. 33.]
  [34. 35. 36.]]

 [[37. 38. 39.]
  [40. 41. 42.]
  [43. 44. 45.]
  [46. 47. 48.]]]
[255. 255. 255. 255. 255. 255. 255. 255. 255. 255. 255. 255.   1.   2.
   3.   4.   5.   6. 255. 255. 255.  13.  14.  15.  16.  17.  18.]

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.
 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36.
 37. 38. 39. 40. 41. 42. 43. 44. 45. 46. 47. 48.]
[[[255. 255. 255. 255. 255.]
  [255. 255. 255. 255. 255.]
  [255. 255. 255. 255. 255.]
  [255. 255. 255. 255. 255.]
  [255. 255. 255. 255. 255.]
  [255. 255. 255. 255. 255.]]

 [[255. 255. 255. 255. 255.]
  [255.   1.   2.   3. 255.]
  [255.   4.   5.   6. 255.]
  [255.   7.   8.   9. 255.]
  [255.  10.  11.  12. 255.]
  [255. 255. 255. 255. 255.]]

 [[255. 255. 255. 255. 255.]
  [255.  13.  14.  1

In [43]:
testStack[:,:,0]
print(testStack.shape)

(4, 4, 3)


In [30]:
testStack[0,1,2]

7.0